com.gw2auth:
  oauth2:
    client:
      s3:
        bucket: ${AWS_S3_SESSION_BUCKET}
        prefix: "oauth2/authorization/"
    addfederation:
      s3:
        bucket: ${AWS_S3_SESSION_BUCKET}
        prefix: "oauth2/addfederation/"
  gw2:
    client:
      aws-lambda-proxy:
        arns: ${AWS_LAMBDA_PROXY_ARNS}

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: cognito
            client-name: "Amazon Cognito"
            client-id: ${AMZ_COGNITO_CLIENT_ID}
            client-secret: ${AMZ_COGNITO_CLIENT_SECRET}
            scope: "openid"
            redirect-uri: "{baseUrl}/auth/oauth2/code/cognito"
          github:
            provider: github
            client-name: "GitHub"
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: [""]
            redirect-uri: "{baseUrl}/auth/oauth2/code/github"
          google:
            provider: google
            client-name: "Google"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: "openid"
            redirect-uri: "{baseUrl}/auth/oauth2/code/google"
        provider:
          cognito:
            issuer-uri: "https://cognito-idp.${AMZ_COGNITO_REGION}.amazonaws.com/${AMZ_COGNITO_POOL_ID}"
            user-name-attribute: sub
          github:
            user-name-attribute: id
          google:
            user-name-attribute: sub
  datasource:
    url: "jdbc:postgresql://${SERVER_POSTGRES_HOST}:${SERVER_POSTGRES_PORT}/${SERVER_POSTGRES_DB}${SERVER_POSTGRES_OPTIONS}"
    username: ${SERVER_POSTGRES_USER}
    password: ${SERVER_POSTGRES_PASSWORD}
    hikari:
      keepalive-time: 60000
      max-lifetime: 600000
  flyway:
    url: "jdbc:postgresql://${SERVER_POSTGRES_HOST}:${SERVER_POSTGRES_PORT}/${SERVER_POSTGRES_DB}${SERVER_POSTGRES_OPTIONS}"
    user: ${SERVER_FLYWAY_POSTGRES_USER}
    password: ${SERVER_FLYWAY_POSTGRES_PASSWORD}

management:
  endpoints:
    enabled-by-default: false