com.gw2auth:
  url: "https://gw2auth.com"
  session:
    priv:
      id: "cd6fb64f-4724-49ad-9ebb-eec6ec3de9ed"
      path: "/opt/app/session_id_rsa_1"
    pub1:
      id: "cd6fb64f-4724-49ad-9ebb-eec6ec3de9ed"
      path: "/opt/app/session_id_rsa_1.pub"
    pub2:
      id: "eb8423b2-3580-4dc8-9805-acf7d9c93af0"
      path: "/opt/app/session_id_rsa_2.pub"
  oauth2:
    keypair:
      id: "9b051022-aeba-4767-9e98-d6f1b7b4d09f"
      path: "/opt/app/id_rsa"

server:
  forward-headers-strategy: framework
  tomcat:
    redirect-context-root: false

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: cognito
            client-name: "Amazon Cognito"
            client-id: ${AMZ_COGNITO_CLIENT_ID}
            client-secret: ${AMZ_COGNITO_CLIENT_SECRET}
            scope: "openid"
            redirect-uri: "{baseUrl}/auth/oauth2/code/cognito"
          github:
            provider: github
            client-name: "GitHub"
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: [""]
            redirect-uri: "{baseUrl}/auth/oauth2/code/github"
          google:
            provider: google
            client-name: "Google"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: "openid"
            redirect-uri: "{baseUrl}/auth/oauth2/code/google"
        provider:
          cognito:
            issuer-uri: "https://cognito-idp.${AMZ_COGNITO_REGION}.amazonaws.com/${AMZ_COGNITO_POOL_ID}"
            user-name-attribute: sub
          github:
            user-name-attribute: id
          google:
            user-name-attribute: sub

management:
  endpoints:
    jmx:
      exposure:
        exclude: prometheus
    web:
      exposure:
        include: prometheus
  server:
    port: 8090
  endpoint:
    prometheus:
      enabled: true