com.gw2auth:
  url: "https://beta.gw2auth.com"
  session:
    priv:
      id: "14c8cabe-2c94-4b7a-92b8-0396d6b2c656"
      path: "/opt/app/session_id_rsa_1"
    pub1:
      id: "14c8cabe-2c94-4b7a-92b8-0396d6b2c656"
      path: "/opt/app/session_id_rsa_1.pub"
    pub2:
      id: "2509411e-fe82-45ad-8af0-d84658cad893"
      path: "/opt/app/session_id_rsa_2.pub"
  oauth2:
    keypair:
      id: "c14e1a11-7351-442c-ba3f-25509c3d0ef2"
      path: "/opt/app/id_rsa"

server:
  forward-headers-strategy: framework
  tomcat:
    redirect-context-root: false

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: gw2auth
            client-name: "Amazon Cognito"
            client-id: ${AMZ_COGNITO_CLIENT_ID}
            client-secret: ${AMZ_COGNITO_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/cognito"
          github:
            provider: gw2auth
            client-name: "GitHub"
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/github"
          google:
            provider: gw2auth
            client-name: "Google"
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/google"
          discord:
            provider: gw2auth
            client-name: "Discord"
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/discord"
        provider:
          gw2auth:
            issuer-uri: "https://gw2auth.com"
            user-name-attribute: sub

management:
  endpoints:
    jmx:
      exposure:
        exclude: prometheus
    web:
      exposure:
        include: prometheus
  server:
    port: 8090
  endpoint:
    prometheus:
      enabled: true