com.gw2auth:
  url: "https://feature.gw2auth.com"
  session:
    priv:
      id: "cb2fb247-8b82-44cb-a9a1-2d5f962df266"
      path: "/opt/app/session_id_rsa_1"
    pub1:
      id: "cb2fb247-8b82-44cb-a9a1-2d5f962df266"
      path: "/opt/app/session_id_rsa_1.pub"
    pub2:
      id: "0da197a4-059d-419e-8272-35f5c8cb6e99"
      path: "/opt/app/session_id_rsa_2.pub"
  oauth2:
    keypair:
      id: "b9582d32-df35-4e95-96e5-d999bf157816"
      path: "/opt/app/id_rsa"

server:
  forward-headers-strategy: framework
  tomcat:
    redirect-context-root: false

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: gw2auth
            client-name: "Amazon Cognito"
            client-id: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_ID}
            client-secret: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/cognito"
          github:
            provider: gw2auth
            client-name: "GitHub"
            client-id: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_ID}
            client-secret: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/github"
          google:
            provider: gw2auth
            client-name: "Google"
            client-id: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_ID}
            client-secret: ${GW2AUTH_LOGIN_PROVIDER_CLIENT_SECRET}
            scope: "id"
            redirect-uri: "{baseUrl}/auth/oauth2/code/google"
        provider:
          gw2auth:
            issuer-uri: "https://gw2auth.com"
            user-name-attribute: sub

management:
  endpoints:
    jmx:
      exposure:
        exclude: prometheus
    web:
      exposure:
        include: prometheus
  server:
    port: 8090
  endpoint:
    prometheus:
      enabled: true