name: "Build"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK 16"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "16"
          cache: "maven"
      - name: "Build"
        run: mvn clean package
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "oauth2-server"
          path: |
            Dockerfile
            docker-entrypoint.sh
            target/oauth2-server.jar
            target/version.txt