name: "Docker"

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 16"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
          cache: "maven"
      - name: "Build"
        run: mvn clean package
      - name: "Build Docker"
        env:
          VERSION_TAG: "${{ github.ref_name }}"
        run: "docker build -t \"gw2auth/oauth2-server:latest\" -t \"gw2auth/oauth2-server:$VERSION_TAG\" ."
      - name: "Login Docker"
        env:
          DOCKER_LOGIN: "${{ secrets.DOCKER_LOGIN }}"
          DOCKER_ACCESS_TOKEN: "${{ secrets.DOCKER_ACCESS_TOKEN }}"
        run: "docker login -u $DOCKER_LOGIN -p $DOCKER_ACCESS_TOKEN"
      - name: "Push Docker"
        run: "docker push \"gw2auth/oauth2-server\" --all-tags"
